### ISSUE TITLE
Move some actions to different action types

### ISSUE THREAD

**Issue by ryanlrussell** [SDNC2/PhantomFloodlight#1]
Floodlight App 0.0.1

(first off, a quick note since this is the first Issue I'm filing. I'm Ryan from Phantom. My CTO has assigned us to have a look at the user-created Phantom Apps to see if there are any suggestions we can make so that everything is consistent, and to see if we can suggest any improvements. We're very pleased to have your Floodlight App for Phantom. Understand that when I put on my QA hat, I have a tendency to run down the checklist and flag everything I see. Obviously, prioritize or don't as appropriate.)

I've noted that a fair number of your Actions are marked as type Generic, and I think a number of them could be in a different category. I believe you have most of the block/unblock ones correctly tagged as contain/correct, though. I'll list my suggested changes below, but the biggest chunk is that any "list" Actions would normally be "investigate".

list static flows:investigate
list devices:investigate
list external links:investigate
list internal links:investigate
list switches:investigate
list firewall rules:investigate
delete firewall rule:correct

**Comment by rsharo** [comment]
@ryanlrussell Thanks!

Changes applied.
