### ISSUE TITLE
Logo could be slightly improved

### ISSUE THREAD

**Issue by ryanlrussell** [SDNC2/PhantomFloodlight#2]
Floodlight App 0.0.1

Here's the logo as it currently appears on our Apps page, with some neighbors for comparison:

![screen shot 2016-06-24 at 2 03 14 pm](https://cloud.githubusercontent.com/assets/1728937/16351023/69141570-3a17-11e6-953f-8b6f08ebbbd1.png)

I can see that there's a little bit of a horizontal line on top of the logo. We would normally want it to be all white (or transparent) in the background. Also, if it were slightly bigger, the scale would match its neighbors a bit better.

**Comment by rsharo** [comment]
@ryanlrussell New icon in the latest commit.
