### ISSUE TITLE
Please bump version number

### ISSUE THREAD

**Issue by ryanlrussell** [SDNC2/PhantomFloodlight#4]
Floodlight App (marked) 0.0.1, but with changes

Thanks for addressing the other reports so quickly, and explaining the unblock ip priority to me.

Could I ask you to bump the version number of the App in the JSON, please? Whatever number scheme you like whether it's 0.0.2, or 0.1.0, etc. Just as long as it's different and higher. I should have mentioned that the first time.

Thanks!

**Comment by rsharo** [comment]
@ryanlrussell done
